package OOPS.assignment_7.CustomException;

public class CustomArithmeticException extends Exception{
    public CustomArithmeticException(){
        super("CustomArithmeticException caught");
    }
}
